version: "3.8"
services:
  postgres-db:
    container_name: portfolio
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5442:5432"

volumes:
  postgresql_data:
    driver: local