spring:
  application:
    name: portfolio

  datasource:
    url: jdbc:postgresql://localhost:5442/portfolio
    driver-class-name: org.postgresql.Driver
    username: portfolio
    password: portfolio
  flyway:
    enabled: true
    locations: classpath:db/migration
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
  server:
    port: 8080
